USE [master]
GO

/****** Object:  Database [PetDb]    Script Date: 10/08/2017 19:09:10 ******/
DROP DATABASE [PetDb]
GO

/****** Object:  Database [PetDb]    Script Date: 10/08/2017 19:09:10 ******/
CREATE DATABASE [PetDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PetDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\PetDb.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PetDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\PetDb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PetDb] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PetDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PetDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PetDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PetDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PetDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PetDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [PetDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PetDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PetDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PetDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PetDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PetDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PetDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PetDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PetDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PetDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PetDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PetDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PetDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PetDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PetDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PetDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PetDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PetDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PetDb] SET  MULTI_USER 
GO

ALTER DATABASE [PetDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PetDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PetDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PetDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PetDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PetDb] SET  READ_WRITE 
GO


